version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    auto-merge: true
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: typescript
        versions:
          - ">= 5"
